# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/shiroko/Projects/MyFirstTouchToRISCV

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/shiroko/Projects/MyFirstTouchToRISCV

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/shiroko/Projects/MyFirstTouchToRISCV/CMakeFiles /home/shiroko/Projects/MyFirstTouchToRISCV//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/shiroko/Projects/MyFirstTouchToRISCV/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named kernel.elf

# Build rule for target.
kernel.elf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kernel.elf
.PHONY : kernel.elf

# fast build rule for target.
kernel.elf/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/build
.PHONY : kernel.elf/fast

kernel/driver/SBI.obj: kernel/driver/SBI.c.obj
.PHONY : kernel/driver/SBI.obj

# target to build an object file
kernel/driver/SBI.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/kernel/driver/SBI.c.obj
.PHONY : kernel/driver/SBI.c.obj

kernel/driver/SBI.i: kernel/driver/SBI.c.i
.PHONY : kernel/driver/SBI.i

# target to preprocess a source file
kernel/driver/SBI.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/kernel/driver/SBI.c.i
.PHONY : kernel/driver/SBI.c.i

kernel/driver/SBI.s: kernel/driver/SBI.c.s
.PHONY : kernel/driver/SBI.s

# target to generate assembly for a file
kernel/driver/SBI.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/kernel/driver/SBI.c.s
.PHONY : kernel/driver/SBI.c.s

kernel/driver/console.obj: kernel/driver/console.c.obj
.PHONY : kernel/driver/console.obj

# target to build an object file
kernel/driver/console.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/kernel/driver/console.c.obj
.PHONY : kernel/driver/console.c.obj

kernel/driver/console.i: kernel/driver/console.c.i
.PHONY : kernel/driver/console.i

# target to preprocess a source file
kernel/driver/console.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/kernel/driver/console.c.i
.PHONY : kernel/driver/console.c.i

kernel/driver/console.s: kernel/driver/console.c.s
.PHONY : kernel/driver/console.s

# target to generate assembly for a file
kernel/driver/console.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/kernel/driver/console.c.s
.PHONY : kernel/driver/console.c.s

kernel/lib/rb_tree.obj: kernel/lib/rb_tree.c.obj
.PHONY : kernel/lib/rb_tree.obj

# target to build an object file
kernel/lib/rb_tree.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/kernel/lib/rb_tree.c.obj
.PHONY : kernel/lib/rb_tree.c.obj

kernel/lib/rb_tree.i: kernel/lib/rb_tree.c.i
.PHONY : kernel/lib/rb_tree.i

# target to preprocess a source file
kernel/lib/rb_tree.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/kernel/lib/rb_tree.c.i
.PHONY : kernel/lib/rb_tree.c.i

kernel/lib/rb_tree.s: kernel/lib/rb_tree.c.s
.PHONY : kernel/lib/rb_tree.s

# target to generate assembly for a file
kernel/lib/rb_tree.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/kernel/lib/rb_tree.c.s
.PHONY : kernel/lib/rb_tree.c.s

kernel/lib/stdlib.obj: kernel/lib/stdlib.c.obj
.PHONY : kernel/lib/stdlib.obj

# target to build an object file
kernel/lib/stdlib.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/kernel/lib/stdlib.c.obj
.PHONY : kernel/lib/stdlib.c.obj

kernel/lib/stdlib.i: kernel/lib/stdlib.c.i
.PHONY : kernel/lib/stdlib.i

# target to preprocess a source file
kernel/lib/stdlib.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/kernel/lib/stdlib.c.i
.PHONY : kernel/lib/stdlib.c.i

kernel/lib/stdlib.s: kernel/lib/stdlib.c.s
.PHONY : kernel/lib/stdlib.s

# target to generate assembly for a file
kernel/lib/stdlib.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/kernel/lib/stdlib.c.s
.PHONY : kernel/lib/stdlib.c.s

kernel/lib/string.obj: kernel/lib/string.c.obj
.PHONY : kernel/lib/string.obj

# target to build an object file
kernel/lib/string.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/kernel/lib/string.c.obj
.PHONY : kernel/lib/string.c.obj

kernel/lib/string.i: kernel/lib/string.c.i
.PHONY : kernel/lib/string.i

# target to preprocess a source file
kernel/lib/string.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/kernel/lib/string.c.i
.PHONY : kernel/lib/string.c.i

kernel/lib/string.s: kernel/lib/string.c.s
.PHONY : kernel/lib/string.s

# target to generate assembly for a file
kernel/lib/string.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/kernel/lib/string.c.s
.PHONY : kernel/lib/string.c.s

kernel/lib/sys/fdt/fdt.obj: kernel/lib/sys/fdt/fdt.c.obj
.PHONY : kernel/lib/sys/fdt/fdt.obj

# target to build an object file
kernel/lib/sys/fdt/fdt.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/kernel/lib/sys/fdt/fdt.c.obj
.PHONY : kernel/lib/sys/fdt/fdt.c.obj

kernel/lib/sys/fdt/fdt.i: kernel/lib/sys/fdt/fdt.c.i
.PHONY : kernel/lib/sys/fdt/fdt.i

# target to preprocess a source file
kernel/lib/sys/fdt/fdt.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/kernel/lib/sys/fdt/fdt.c.i
.PHONY : kernel/lib/sys/fdt/fdt.c.i

kernel/lib/sys/fdt/fdt.s: kernel/lib/sys/fdt/fdt.c.s
.PHONY : kernel/lib/sys/fdt/fdt.s

# target to generate assembly for a file
kernel/lib/sys/fdt/fdt.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/kernel/lib/sys/fdt/fdt.c.s
.PHONY : kernel/lib/sys/fdt/fdt.c.s

kernel/lib/sys/fdt/libfdt.obj: kernel/lib/sys/fdt/libfdt.c.obj
.PHONY : kernel/lib/sys/fdt/libfdt.obj

# target to build an object file
kernel/lib/sys/fdt/libfdt.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/kernel/lib/sys/fdt/libfdt.c.obj
.PHONY : kernel/lib/sys/fdt/libfdt.c.obj

kernel/lib/sys/fdt/libfdt.i: kernel/lib/sys/fdt/libfdt.c.i
.PHONY : kernel/lib/sys/fdt/libfdt.i

# target to preprocess a source file
kernel/lib/sys/fdt/libfdt.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/kernel/lib/sys/fdt/libfdt.c.i
.PHONY : kernel/lib/sys/fdt/libfdt.c.i

kernel/lib/sys/fdt/libfdt.s: kernel/lib/sys/fdt/libfdt.c.s
.PHONY : kernel/lib/sys/fdt/libfdt.s

# target to generate assembly for a file
kernel/lib/sys/fdt/libfdt.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/kernel/lib/sys/fdt/libfdt.c.s
.PHONY : kernel/lib/sys/fdt/libfdt.c.s

kernel/lib/sys/spinlock.obj: kernel/lib/sys/spinlock.c.obj
.PHONY : kernel/lib/sys/spinlock.obj

# target to build an object file
kernel/lib/sys/spinlock.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/kernel/lib/sys/spinlock.c.obj
.PHONY : kernel/lib/sys/spinlock.c.obj

kernel/lib/sys/spinlock.i: kernel/lib/sys/spinlock.c.i
.PHONY : kernel/lib/sys/spinlock.i

# target to preprocess a source file
kernel/lib/sys/spinlock.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/kernel/lib/sys/spinlock.c.i
.PHONY : kernel/lib/sys/spinlock.c.i

kernel/lib/sys/spinlock.s: kernel/lib/sys/spinlock.c.s
.PHONY : kernel/lib/sys/spinlock.s

# target to generate assembly for a file
kernel/lib/sys/spinlock.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/kernel/lib/sys/spinlock.c.s
.PHONY : kernel/lib/sys/spinlock.c.s

kernel/memory/memory.obj: kernel/memory/memory.c.obj
.PHONY : kernel/memory/memory.obj

# target to build an object file
kernel/memory/memory.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/kernel/memory/memory.c.obj
.PHONY : kernel/memory/memory.c.obj

kernel/memory/memory.i: kernel/memory/memory.c.i
.PHONY : kernel/memory/memory.i

# target to preprocess a source file
kernel/memory/memory.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/kernel/memory/memory.c.i
.PHONY : kernel/memory/memory.c.i

kernel/memory/memory.s: kernel/memory/memory.c.s
.PHONY : kernel/memory/memory.s

# target to generate assembly for a file
kernel/memory/memory.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/kernel/memory/memory.c.s
.PHONY : kernel/memory/memory.c.s

kernel/memory/pool.obj: kernel/memory/pool.c.obj
.PHONY : kernel/memory/pool.obj

# target to build an object file
kernel/memory/pool.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/kernel/memory/pool.c.obj
.PHONY : kernel/memory/pool.c.obj

kernel/memory/pool.i: kernel/memory/pool.c.i
.PHONY : kernel/memory/pool.i

# target to preprocess a source file
kernel/memory/pool.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/kernel/memory/pool.c.i
.PHONY : kernel/memory/pool.c.i

kernel/memory/pool.s: kernel/memory/pool.c.s
.PHONY : kernel/memory/pool.s

# target to generate assembly for a file
kernel/memory/pool.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/kernel/memory/pool.c.s
.PHONY : kernel/memory/pool.c.s

kernel/startup/startup.obj: kernel/startup/startup.S.obj
.PHONY : kernel/startup/startup.obj

# target to build an object file
kernel/startup/startup.S.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/kernel/startup/startup.S.obj
.PHONY : kernel/startup/startup.S.obj

kernel/startup/startup.obj: kernel/startup/startup.c.obj
.PHONY : kernel/startup/startup.obj

# target to build an object file
kernel/startup/startup.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/kernel/startup/startup.c.obj
.PHONY : kernel/startup/startup.c.obj

kernel/startup/startup.i: kernel/startup/startup.c.i
.PHONY : kernel/startup/startup.i

# target to preprocess a source file
kernel/startup/startup.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/kernel/startup/startup.c.i
.PHONY : kernel/startup/startup.c.i

kernel/startup/startup.s: kernel/startup/startup.c.s
.PHONY : kernel/startup/startup.s

# target to generate assembly for a file
kernel/startup/startup.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kernel.elf.dir/build.make CMakeFiles/kernel.elf.dir/kernel/startup/startup.c.s
.PHONY : kernel/startup/startup.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... kernel.elf"
	@echo "... kernel/driver/SBI.obj"
	@echo "... kernel/driver/SBI.i"
	@echo "... kernel/driver/SBI.s"
	@echo "... kernel/driver/console.obj"
	@echo "... kernel/driver/console.i"
	@echo "... kernel/driver/console.s"
	@echo "... kernel/lib/rb_tree.obj"
	@echo "... kernel/lib/rb_tree.i"
	@echo "... kernel/lib/rb_tree.s"
	@echo "... kernel/lib/stdlib.obj"
	@echo "... kernel/lib/stdlib.i"
	@echo "... kernel/lib/stdlib.s"
	@echo "... kernel/lib/string.obj"
	@echo "... kernel/lib/string.i"
	@echo "... kernel/lib/string.s"
	@echo "... kernel/lib/sys/fdt/fdt.obj"
	@echo "... kernel/lib/sys/fdt/fdt.i"
	@echo "... kernel/lib/sys/fdt/fdt.s"
	@echo "... kernel/lib/sys/fdt/libfdt.obj"
	@echo "... kernel/lib/sys/fdt/libfdt.i"
	@echo "... kernel/lib/sys/fdt/libfdt.s"
	@echo "... kernel/lib/sys/spinlock.obj"
	@echo "... kernel/lib/sys/spinlock.i"
	@echo "... kernel/lib/sys/spinlock.s"
	@echo "... kernel/memory/memory.obj"
	@echo "... kernel/memory/memory.i"
	@echo "... kernel/memory/memory.s"
	@echo "... kernel/memory/pool.obj"
	@echo "... kernel/memory/pool.i"
	@echo "... kernel/memory/pool.s"
	@echo "... kernel/startup/startup.obj"
	@echo "... kernel/startup/startup.obj"
	@echo "... kernel/startup/startup.i"
	@echo "... kernel/startup/startup.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

